
[package]
name = 'counter_contract'
type = 'contract'
authors = [
  '',
]
compiler_version = '0.18'

[dependencies]
aztec = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.14.2', directory = 'yarn-project/aztec-nr/aztec' }
value_note = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.14.2', directory = 'yarn-project/aztec-nr/value-note' }
easy_private_state = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.14.2', directory = 'yarn-project/aztec-nr/easy-private-state' }
